Repository tailscale-dev/tclip, pull requests merged in 2024-07, with the labels that each got.

#44 *: fix forgotten renames from web to tclipd
  README.md
  package.json
  tailwind.config.js
Labels: documentation

#53 Upgrade all dependencies
  cmd/tclipd/static/css/base.css
  flake.lock
  flake.nix
  go.mod
  go.sum
  gomod2nix.toml
  package.json
  yarn.lock
Labels: dependencies

#51 Option to hide paste creator for funneled pastes
  cmd/tclipd/main.go
  cmd/tclipd/tmpl/showpaste.html
Labels: enhancement

#52 Allow binding to HTTP port
  cmd/tclipd/main.go
Labels: enhancement

#60 Upgrade Tailscale to 1.70.0
  go.mod
  go.sum
  gomod2nix.toml
Labels: dependencies
